- README.md
- crates/ursa-index-provider/src/config.rs
- crates/ursa-index-provider/src/provider.rs
- crates/ursa-metrics/Cargo.toml
- crates/ursa-metrics/src/config.rs
- crates/ursa-network/src/behaviour.rs
- crates/ursa-network/src/config.rs
- crates/ursa-network/src/discovery.rs
- crates/ursa-network/src/gossipsub.rs
- crates/ursa-network/src/service.rs
- crates/ursa-network/src/transport.rs
- crates/ursa-rpc-server/src/api.rs
- crates/ursa-rpc-server/src/config.rs
- crates/ursa-rpc-server/src/rpc/rpc.rs
- crates/ursa-rpc-server/src/server.rs
- crates/ursa/Cargo.toml
- crates/ursa/build.rs
- crates/ursa/src/config.rs
- crates/ursa/src/main.rs
- crates/ursa/src/ursa/mod.rs
- infra/ursa/docker-compose.yml
* create config file on compilation
* add customized ursa config
* config changes in Readme
> chore: config refactor

- crates/ursa-index-provider/src/provider.rs
- crates/ursa-network/Cargo.toml
- crates/ursa-network/src/behaviour.rs
- crates/ursa-network/src/service.rs
- crates/ursa-rpc-server/src/api.rs
- infra/ursa/data/nginx/app.conf
add http announce for advertisement when gossiping over indexer/ingest fails, gossip issue will be tackled under another PR.
> chore: http announce

- crates/ursa-index-provider/src/advertisement.rs
- crates/ursa-index-provider/src/provider.rs
- crates/ursa-network/src/service.rs
steps:
1. start local indexer at `0.0.0.0:3001`
2. update provider config `indexer_url`
3. start local node
4. put car
5. query index provider example
```bash
$ curl http://localhost:8070/head | jq
{
"head": {
"/": "bafy2bzacebl3qjo37qy7xdhtirprvonh4gy3hwtcfivljhh4p2aymfdctfqdm"
},
"sig": {
"/": {
"bytes": "79wCB6pe1BNlmEEQ29iaJL4iPmIbjamS0aMUoF9ErRH1p9idW/+twRaH6WX2YSXFCMicjR+Q+p9suI7q/0y9BA=="
}
},
"pubkey": {
"/": {
"bytes": "CAESIMvdEIOZ/dqnatFO2kcf2bQA+xd5LNKlMUWSuitAOIYm"
}
}
}
$ curl http://localhost:8070/bafy2bzacebl3qjo37qy7xdhtirprvonh4gy3hwtcfivljhh4p2aymfdctfqdm | dagconv | jq
{
"Addresses": [
"/ip4/127.0.0.1/tcp/8070"
],
"ContextID": {
"/": {
"bytes": "AXASILhKdBSed2P1vtVlIRGPyz6OcX2skalVsD9Nw3kTGgYi"
}
},
"Entries": {
"/": …
```
> feat: network indexing

- README.md
> docs(readme): add social and github ci badges

- infra/ursa/data/grafana/dashboards/ursa.json
- new list of agents running
- map tweaks
- minor tweaks to names
- align display types for connection rate graphs
> chore: update ursa.json to latest grafana changes

- Cargo.toml
- crates/ursa-index-provider/Cargo.toml
- crates/ursa-metrics/Cargo.toml
- crates/ursa-telemetry/Cargo.toml
- crates/ursa-telemetry/src/lib.rs
- crates/ursa/Cargo.toml
- crates/ursa/src/main.rs
- crates/ursa/src/ursa/mod.rs
Usage:
```rust
use telemetry_subscribers::TelemetryConfig;
TelemetryConfig::new("service").init();
// code
TelemetryConfig::teardown();
```
> feat: ursa-telemetry

- crates/ursa-gateway/src/cache/tlrfu.rs
- crates/ursa-gateway/src/main.rs
- crates/ursa-gateway/src/resolver/mod.rs
- crates/ursa-gateway/src/worker/cache.rs
- crates/ursa-gateway/src/worker/mod.rs
> feat: gateway cache improve

- crates/ursa-gateway/src/resolver/mod.rs
> chore: gateway handle indexer not found

- crates/ursa-gateway/.gitignore
- crates/ursa-gateway/Cargo.toml
- crates/ursa-gateway/src/admin/mod.rs
- crates/ursa-gateway/src/cache/tlrfu.rs
- crates/ursa-gateway/src/cli.rs
- crates/ursa-gateway/src/config.rs
- crates/ursa-gateway/src/main.rs
- crates/ursa-gateway/src/resolver/mod.rs
- crates/ursa-gateway/src/server/mod.rs
- crates/ursa-gateway/src/server/route/api/v1/get.rs
- crates/ursa-gateway/src/worker/cache.rs
- crates/ursa-gateway/src/worker/mod.rs
#198 
```bash
$ curl http://0.0.0.0:4069/bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei -v > origin
$ curl https://0.0.0.0:80/bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei -k -v > gateway
$ openssl dgst -sha256 origin | awk '/.+$/{print "0x"$2}'
0x38b4a497f9ceea9d4fd024ee0d16b9989b71be2d4e8e10eaa67091d5db32f33e
$ openssl dgst -sha256 gateway | awk '/.+$/{print "0x"$2}'
0x38b4a497f9ceea9d4fd024ee0d16b9989b71be2d4e8e10eaa67091d5db32f33e
```
> feat: gateway streaming handler

- crates/ursa-gateway/src/resolver/mod.rs
- crates/ursa-gateway/src/server/route/api/v1/get.rs
- crates/ursa-gateway/src/util/error.rs
- crates/ursa-gateway/src/util/mod.rs
- crates/ursa-gateway/src/worker/cache.rs
> chore: propagate upstream errors to clients

- crates/ursa-gateway/src/admin/mod.rs
- crates/ursa-gateway/src/cli.rs
- crates/ursa-gateway/src/config.rs
- crates/ursa-gateway/src/main.rs
- crates/ursa-gateway/src/server/mod.rs
- crates/ursa-gateway/src/worker/mod.rs
> feat: gateway graceful shutdown

- crates/ursa-gateway/Cargo.toml
- crates/ursa-gateway/src/cli.rs
- crates/ursa-gateway/src/config.rs
- crates/ursa-gateway/src/main.rs
- crates/ursa-gateway/src/server/mod.rs
- crates/ursa-gateway/src/worker/cache.rs
> feat: gateway config improvement

- crates/ursa/src/main.rs
https://github.com/fleek-network/ursa/pull/223
extracts some needed changs from this PR
> chore: lower log level to info

- .github/workflows/_docker-publish.yml
- .github/workflows/_rust.yml
- .github/workflows/docker-publish.yml
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
> chore: cyclical workflow 🫣

- crates/ursa-gateway/src/admin/mod.rs
- crates/ursa-gateway/src/admin/route/api/v1/post.rs
- crates/ursa-gateway/src/cli.rs
- crates/ursa-gateway/src/config.rs
- crates/ursa-gateway/src/main.rs
- crates/ursa-gateway/src/server/mod.rs
- crates/ursa-gateway/src/server/route/api/v1/get.rs
- crates/ursa-gateway/src/worker/cache.rs
- crates/ursa-gateway/src/worker/cache/admin.rs
- crates/ursa-gateway/src/worker/cache/mod.rs
- crates/ursa-gateway/src/worker/cache/server.rs
- crates/ursa-gateway/src/worker/cache/worker.rs
- crates/ursa-gateway/src/worker/mod.rs
#172 
```bash
$ curl -k https://0.0.0.0:80/bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei \
-H 'cache-control: no-cache'
```
Server log:
```
2023-01-05T19:18:44.897418Z  INFO ursa_gateway::worker: Dispatch FetchAnnounce command with cid: "bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei"
...
2023-01-05T19:18:44.901371Z  INFO ursa_gateway::worker: Dispatch InsertSyncAnnounce command with key: "bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei"
```
> feat: cache invalidation

- crates/ursa-gateway/README.md
- crates/ursa-gateway/example/local.toml
- crates/ursa-gateway/example/node.toml
- Fixes #266 
- Gateway document
N/A
N/A
> chore: gateway doc

- .github/pull_request_template.md
Expected behaviour
- Remove `I have performed a self-review and commented my code, particularly in complex areas`
> chore: pull_request_template.md

- test-plans/data-transfer/Cargo.toml
- test-plans/data-transfer/_compositions/rust.toml
- test-plans/data-transfer/manifest.toml
- test-plans/data-transfer/src/bootstrap.rs
In the testground testplan, all the nodes bootstrap approximately at the same time. 
This can lead to bootstrapping failures and furthermore is not representative of real networking behavior.
Instead, bootstrapping will be done in batches. Nodes are divided into batches of `K` nodes (atm `K=5`).
- Nodes are divided into batches of size `K`.
- Nodes in a batch always wait for the previous batch to finish bootstrapping before starting the bootstrapping process.
In collaboration with @kckeiks.
> feat: refined bootstrapping for testplan

- test-plans/data-transfer/Cargo.toml
- test-plans/data-transfer/src/bootstrap.rs
- test-plans/data-transfer/src/cache.rs
- test-plans/data-transfer/src/main.rs
- test-plans/data-transfer/src/node.rs
Passes node service state to other tests after bootstrapping.
- N/A I have made corresponding changes to the tests
- N/A I have made corresponding changes to the documentation
- N/A I have run the app using my feature and ensured that no functionality is broken
> chore: add node abstraction

- Cargo.toml
- crates/ursa-gateway/Cargo.toml
- crates/ursa-gateway/src/main.rs
- crates/ursa-gateway/src/resolver/mod.rs
- crates/ursa-gateway/src/server/mod.rs
- crates/ursa-gateway/src/server/route/api/v1/get.rs
- crates/ursa-gateway/src/worker/cache/mod.rs
- crates/ursa-gateway/src/worker/cache/server.rs
- crates/ursa-gateway/src/worker/mod.rs
- crates/ursa-telemetry/src/lib.rs
gateway opentelemetry & tracing
Fixes:
- #276 
- #285 
- improve ursa-telemetry
- integrate tracing to gateway
N/A
> feat: gateway otel & tracing

- test-plans/data-transfer/src/cache.rs
- test-plans/data-transfer/src/main.rs
- test-plans/data-transfer/src/pull.rs
We want to benchmark how fast nodes can transfer (pull) data.
Task of #264 
Tests that nodes pull data.
- N/A I have made corresponding changes to the tests
- N/A I have made corresponding changes to the documentation
> feat: pull request test plan

- test-plans/data-transfer/src/pull.rs
Using tokio's timeout causes tests to finish at around the timeout time which prevents us from getting accurate results. 
Use a loop and Duration to signal that the data was pulled and is in store.
```
Jan 17 22:11:46.230355	INFO	0.0000s    MESSAGE << data-transfer[001] (4878ab) >> [Pull] Results for node 6: 27.293666ms
Jan 17 22:11:46.230369	INFO	0.0000s    MESSAGE << data-transfer[003] (e97577) >> [Pull] Results for node 3: 78.670541ms
Jan 17 22:11:46.230388	INFO	0.0000s    MESSAGE << data-transfer[009] (efe6b8) >> [Pull] Results for node 5: 58.417667ms
Jan 17 22:11:46.230405	INFO	48.3269s         OK << data-transfer[001] (4878ab) >> 
Jan 17 22:11:46.230428	INFO	0.0000s    MESSAGE << data-transfer[004] (c8c83d) >> [Pull] Results for node 4: 93.487501ms
Jan 17 22:11:46.230430	INFO …
```
> fix: get accurate time metrics

- crates/ursa/src/ursa/identity.rs
opening openssl generated ed25519 keys bugs out since they do not include a public key
- dont check byte length
- use SecretKey Into<Keypair> and only use the sk bytes, ignore pubkey
> fix: openssl generated ed25519 pem encoding compat

- docker/gateway-node/docker-compose.yml
Fixes #312 
- add jager
N/A
N/A
> chore(gateway): docker jaeger

- docker/full-node/data/grafana/grafana.ini
- docker/global-metrics/data/grafana/dashboards/ursa.json
- docker/global-metrics/docker-compose.yml
- Resolve grafana config issues in global metrics
- set max hold time for prometheus entries
- prometheus max time of 200hr
- corect grafana config
- update global ursa.json
- add missing grafana.ini to full-node
> chore: update global metrics

- crates/ursa-gateway/src/server/mod.rs
Trace id should be returned.
Fixes #315 
- Return `trace_id`
Example:
```
< HTTP/2 500
< content-type: application/json
< content-length: 122
< trace_id: af8b3e5a8462eb8e0268128f71dab81d
< x-request-id: c78da63a-22d8-4113-ad29-cdce50f89318
< access-control-allow-origin: *
< vary: origin
< vary: access-control-request-method
< vary: access-control-request-headers
< date: Thu, 19 Jan 2023 21:25:42 GMT
```
N/A
> chore(gateway): trace_id response header

- crates/ursa-gateway/example/local.toml
- crates/ursa-gateway/example/node.toml
- crates/ursa-gateway/src/admin/mod.rs
- crates/ursa-gateway/src/cli.rs
- crates/ursa-gateway/src/config.rs
Fixes #308 
- Remove admin server tls
N/A
N/A
> chore(gateway): remove admin server tls

- test-plans/fetching/Cargo.toml
- test-plans/fetching/Dockerfile
- test-plans/fetching/_compositions/rust.toml
- test-plans/fetching/manifest.toml
- test-plans/fetching/src/bootstrap.rs
- test-plans/fetching/src/lib.rs
- test-plans/fetching/src/main.rs
- test-plans/fetching/src/node.rs
See https://github.com/fleek-network/ursa/issues/271. This allows us to benchmark how fast nodes can retrieve content from their peers using bitswap.
- Added new test plan to test and benchmark bitswap retrieval from peers.
> test: content discovery/fetching test plan

- test-plans/data-transfer/src/pull.rs
- test-plans/fetching/src/lib.rs
See https://github.com/fleek-network/ursa/issues/337.
- Adds generous timeouts to barriers in testground test plans to avoid tests getting stuck
> tests: prevent blocking at barriers

- docker/full-node/README.md
- docker/full-node/init-letsencrypt.sh
Prevents the end-user from having to edit the file, in the same manner, we do for domains.
- Modified the init letsencrypt script
- Updated the doc included in the location where the script is stored
> refactor: 💡 init-letsencrypt, email as argument

- docker/full-node/README.md
minor updates for the full node readme
- correct paths
- add ping healthcheck
- [~] I have made corresponding changes to the tests
- [~] I have made corresponding changes to the documentation
- [~] I have run the app using my feature and ensured that no functionality is broken
> docs: minor update for docker full node readme

- .github/workflows/rust.yml
- Dockerfile
- Dockerfile-gateway
- Makefile
fixes ci pipeline ( https://github.com/mcginty/snow/issues/146 )
- add `cargo update -p curve25519-dalek@4.0.0-rc.0 --precise 4.0.0-pre.5` to:
- dockerfile
- rust ci
- makefile: `make fix-deps` for an easy local fix
> hotfix: snow dependency bug

- .github/workflows/rust.yml
- Dockerfile
- Dockerfile-gateway
- Makefile
Reverts fleek-network/ursa#349
> Revert "hotfix: snow dependency bug"

- crates/ursa-network/src/config.rs
- crates/ursa-network/src/service.rs
Resolves #73 
- add `network_config.kad_walk_interval` (defaulting to 300 seconds / 5 minutes)
- add timer to trigger random kad walks in service.rs
(for the demo, lowered the delay to 1s just to grab a screenshot quickly)
- ~~I have made corresponding changes to the tests~~
- ~~I have made corresponding changes to the documentation~~
> feat: random kademlia walks

- crates/ursa-proxy/src/config.rs
- crates/ursa-proxy/src/core/handler.rs
- crates/ursa-proxy/src/core/mod.rs
- crates/ursa-proxy/src/lib.rs
- crates/ursa-proxy/src/main.rs
This will allow us to reuse some code in the gateway.
- Move code to lib.rs #327 
- Remove `no_cache` from config.
- Use type headers to extract cache control headers.
> chore(proxy): move code into a library

- crates/ursa-gateway/src/config.rs
Fixes #367 
- Default self-signed cert
N/A
N/A
> chore(gateway): default self-signed cert

- crates/ursa-gateway/Cargo.toml
Fixes #378 
clean up deps
N/A
N/A
> chore(gateway): clean up deps

- crates/ursa-gateway/src/server/mod.rs
- crates/ursa-gateway/src/server/route/api/v1/get.rs
Fixes #292 
- IPFS spec
N/A
N/A
> chore(gateway): ipfs spec

- crates/ursa-consensus/Cargo.toml
- because we have to be consistent
- Change `Cargo.toml`
> chore: add cargo package stuff

- docker/full-node/docker-compose.yml
Declaring a health-check will provide the status of the container, which then I can give a kill signal to have the ursa serve always to restart.
- Docker compose yaml, ursa's service declaration
> chore: 🤖 docker stack ursa health-check

- docker/full-node/docker-compose.yml
Given the health-check status (https://github.com/fleek-network/ursa/pull/415), the service is restarted.
- Docker compose yaml config
> perf: ⚡️ ursa restart when unhealthy

- crates/ursa-network/src/measurements/mod.rs
See https://github.com/fleek-network/ursa/issues/487.
- Changed latency type to `u32`, bandwidth type to `u64`, and uptime type to `u128`.
- Added peer_id to measurements struct
- Removed option wrappers. If one of the three measurements is missing, none will be reported.
> feat: make peer measurements compatible with solidity

- crates/ursa-proxy/Cargo.toml
- crates/ursa-proxy/src/cache/moka_cache.rs
- crates/ursa-proxy/src/core/handler.rs
- crates/ursa-proxy/src/core/mod.rs
- crates/ursa-proxy/src/main.rs
* Adds logging.
* Adds tracing.
> feat(proxy): add logging

- crates/ursa-proxy/example/example.toml
- crates/ursa-proxy/src/config.rs
- crates/ursa-proxy/src/core/handler.rs
- crates/ursa-proxy/src/main.rs
Allow users to configure proxy.
- Configure log level.
- Configure the size of the buffer used when copying data to cache.
> feat(proxy): add missing configurability 

- Dockerfile-proxy
Decoupled the Dockerfile-proxy file from https://github.com/fleek-network/ursa/pull/506
- Dockerfile for ursa-proxy
⚠️ Relates to https://github.com/fleek-network/ursa/pull/509
> chore: 🤖 add Dockerfile-proxy

- crates/ursa-pod/spec/README.md
adds the initial spec for v0 ufdp, I've had this locally for a little while and figured I'd push it
I originally had the codec documented in a separate file, `spec/CODEC.md`. I'm undecided what would be better
- [-] I have made corresponding changes to the tests
- [-] I have run the app using my feature and ensured that no functionality is broken
> docs(pod): add v0 codec spec in markdown

- crates/ursa-pod/spec/README.md
UFDP Spec has some typos
- Change 1
- Change 2
- Change 3
> docs: ✏️ ufdp spec text amends

- crates/ursa-gateway/src/resolver/round_robin.rs
Unwrap should not have been added.
> fix: remove unwrap
