fleek-network/ursa

- README.md
Adds the local dependencies needed to compile and run the project.
When using docker, only `make` is needed
> docs: dependencies

- crates/ursa-network/src/behaviour.rs
`Behaviour`'s poll method was unregistered in #65. This registers it again.
> Register poll method

- Makefile
The docker-run would ultimately run the docker container without exposing the necessary ports to the host, thus this PR declares it.
> fix: 🐛 bind docker container ports to host

- crates/ursa-rpc-client/src/lib.rs
- crates/ursa-rpc-server/src/api.rs
We are unwrapping a lot in the rpc code, which causes panics and no response to the client. We should properly return errors to the client.
Node:
Client:
> fix: properly handle cid not found in blockstore

- Cargo.toml
- crates/ursa-gateway/Cargo.toml
- crates/ursa-gateway/src/indexer/model.rs
- crates/ursa-index-provider/Cargo.toml
- crates/ursa-index-provider/src/advertisement.rs
- crates/ursa-index-provider/src/provider.rs
- crates/ursa-index-provider/src/tests/provider_tests.rs
- crates/ursa-metrics/Cargo.toml
- crates/ursa-network/Cargo.toml
- crates/ursa-network/src/tests/service_tests.rs
- crates/ursa-rpc-client/Cargo.toml
- crates/ursa-rpc-client/src/lib.rs
- crates/ursa-rpc-server/Cargo.toml
- crates/ursa-rpc-server/src/http/routes/network.rs
- crates/ursa-rpc-server/src/rpc/rpc.rs
- crates/ursa-store/Cargo.toml
- crates/ursa/Cargo.toml
motivation: A few of the dependencies in multiple crates were using different versions. Recently, [the dependency inheritance](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace) was added to cargo. so this would be a good way of managing dependencies and update them faster as we move on.
> chore: workspace dependencies

- crates/ursa-rpc-client/src/functions.rs
- crates/ursa-rpc-client/src/lib.rs
- crates/ursa/src/ursa/mod.rs
- crates/ursa/src/ursa/rpc_commands.rs
This adds the option to specify the port for cli rpc requests. Sending rpc requests to different ports is useful for developing and debugging. This change is backwards compatible.
For example, to send a put request to port 4071:
```
ursa rpc put <file> --port 4071
```
Without the `--port` option, the port for the request will be taken from [here](https://github.com/fleek-network/ursa/blob/main/crates/ursa-rpc-server/src/config.rs), as before:
```
ursa rpc put <file>
```
> feat: add option to specify the port for cli rpc requests

- infra/ursa/docker-compose.yml
fixes for `infra/ursa/docker-compose.yml`:
- update grafana version
- expose proper ports and update comments
> chore: update ursa docker compose to latest grafana and expose all ports

- crates/ursa/src/main.rs
- crates/ursa/src/ursa/mod.rs
Ursa bin is not consistently setting a default log level and thus requires some to set it locally. This makes the default, and further tweaking the level, much easier and mimicking the [functionality from the gateway](https://github.com/fleek-network/ursa/blob/main/crates/ursa-gateway/src/cli.rs#L12-L14).
- Add `--log, -l <level>` cli opt
- use cli opt, fallback to RUST_LOG, and finally use `info` as default
> feat(ursa): `--log, -l <level>` cli opt, fallback, and default

- README.md
- infra/global-metrics/docker-compose.yml
Docker compose grafana instance is looking for `grafana.ini` at `/etc/grafana/`. We link the global-metrics grafana data to `/var/lib/grafana/`, so should specify the config location to that path to correctly load it.
Also slipped in a small doc update that was left out from #81 (remove `metrics_config` from readme example config)
> fix(global metrics): provide `grafana.ini` config directly

- crates/ursa-tracker/src/types.rs
Tracker should surface registered agent versions as a Prometheus label.
The data is already collected via tracker just not exposed currently
> feat(tracker): surface registered agent versions as prometheus label.

- infra/global-metrics/Dockerfile
Dockerfile used `/` as workdir instead of `/root` resulting in rocks using `/tracker_db` instead of the linked volume `/root/tracker_db`. 
- update paths in tracker dockerfile
> fix(tracker): dockerfile running in incorrect workdir

- crates/ursa-index-provider/src/engine.rs
- crates/ursa-index-provider/src/tests/mod.rs
- crates/ursa-rpc-service/src/tests/mod.rs
- crates/ursa/src/main.rs
Blocks #158 
**Motivation**
The address of the server from which advertised content is retrievable wasn't being advertised.
> fix: advertise server address

- crates/ursa-network/src/service.rs
Some swarm metrics are being missed due to the record happening in the catchall in the match. Since #180 ConnectionEstablished/Closed are handled there, so they were not longer getting recorded. This puts the swarm event record call first, so there's no chance of missing metrics
(paired with #190 we now have some nice numbers for connected peers)
> fix(metrics): ensure all swarm metrics are recorded

- crates/ursa-network/src/codec/protocol.rs
- crates/ursa-network/src/service.rs
- crates/ursa-network/src/tests/service_tests.rs
Clean version of #186 (will be closed).
**Motivation:**
Each node is responsible for replicating its cached content onto its connected peers. After receiving a PUT request, a node will send a caching request to its connected peers.
> feat: send cache request to peers after PUT request

- Dockerfile
- Makefile
- Sequential docker builds are slower considering cargo builds all dependencies every time from scratch
- the dockerfile is building every single binary found in the project, instead of just the ursa bin specifically.
- no easy make helper to rebuild the docker-compose ursa image 
Adds [cargo-chef](https://github.com/LukeMathWalker/cargo-chef) caching to our docker file to take advantage of docker layers to not have to build all dependencies from scratch every time. This saves time by several minutes after the first build, so for node operators updating the deploy time is much sooner, as well as reducing build time for node development.
Also adds a new makescript `compose-build` to build ursa binary within the docker-compose context
First build:
Next builds with cached layers:
> feat: `make compose-build` + only build ursa binary in dockerfile

- .github/workflows/docker-publish.yml
- .github/workflows/rust.yml
- .github/workflows/terraform.yml
- crates/ursa-index-provider/src/tests/provider_tests.rs
- crates/ursa-network/src/service.rs
- crates/ursa-network/src/tests/service_tests.rs
- crates/ursa-rpc-service/src/tests/api_test.rs
- crates/ursa-rpc-service/src/tests/mod.rs
- crates/ursa/src/main.rs
> chore: codecov and job isolation

- Cargo.toml
- crates/ursa-network/Cargo.toml
- crates/ursa-network/src/lib.rs
- crates/ursa-network/src/service.rs
- crates/ursa-network/src/tests/service_tests.rs
- crates/ursa-network/src/utils/bloom_filter.rs
- crates/ursa-network/src/utils/mod.rs
- crates/ursa-rpc-service/src/api.rs
**Motivation:**
Cache nodes use bloom filters to keep track of the set of objects stored in their cache. Nodes share their bloom filters with the network. Nodes will keep track of the bloom filters that were sent by other nodes. When a requested CID is not in a node's cache, a node can search through the bloom filters of other nodes to find the CID.
**Changes:**
* After receiving a PUT request, a node will update its bloom filter and publish it via gossipsub
* Counting bloom filters are used because they have a remove operation (useful for cache eviction)
* If a node receives a gossipsub message containing a bloom filter from another node, it will store the bloom filter in a map <del>(unless the sender is blacklisted)</del>
**Future work:**
* Bloom filters should be persisted to disk
* …
> feat: nodes exchange bloom filters

- crates/ursa-network/src/behaviour.rs
- crates/ursa-network/src/service.rs
start the bootstrap sooner, currently getting an error bootstrap timed out with no more bootstraps remaining. This seems to fix that getting 8+ bootstraps remaining after the first one instead of none. 
Manually tested + unit tested, there are still some timeouts but the bootstrap keeps going. While the bootstrap are returning some odd peer ids (`1AdivKqEdvpxsBm1yQjTRYbqk7MdfVjRmQAzxm752XQVZ6` vs our peer ids which always look like: `12D3KooWN2GSWDQwtRWsgiYXDgCHX5scrdHQPman3tBH2WtyCyK3`), it seems to be working. during the time it took to get to the final bootstrap response, the node had peer connection events for 30+ new peers. I think some timeouts are from peers that had id's switch and are no longer available at the /p2p/<id> address that might still persist in some routing tables …
> refactor(kad): start initial bootstrap from behaviour.rs sooner + improve logs

- Cargo.toml
- crates/ursa-index-provider/src/config.rs
- crates/ursa-network/src/config.rs
- crates/ursa-rpc-service/src/config.rs
- crates/ursa/Cargo.toml
- crates/ursa/src/config.rs
- crates/ursa/src/ursa/mod.rs
ursa bin errors if config is invalid
- Provide deserialization defaults to automatically populate missing values
- Calculate unified diff on the toml we end up with after parsing
- If changes were made, log the diff and save the new config to file
Example showing loading a config with some fields removed and old invalid fields added
We can also easily rename a field by modifying an attribute on a field like so:
```rust 
#[derive(Deserialize)]
struct ExampleConfig {
#[serde(
default = "default_example_fn",
rename(deserialize = "old_name", deserialize = "new_name")
)]
new_name: String,
}
```
Which would result in the old name getting overwritten while preserving the value due to serializing into the new name
- This is currently implemented to be non-blocking and just a warning to avoid …
> feat: auto-upgraded configs using defaults + log the differences

- crates/ursa-network/src/service.rs
- crates/ursa-rpc-service/src/api.rs
- crates/ursa-rpc-service/src/tests/api_test.rs
Omitting the receiver for `NetworkCommand::Put` was causing rpc put requests to fail.
Thanks to @scott-dn for pointing this out.
> fix: rpc put

- crates/ursa-network/src/codec/protocol.rs
- crates/ursa-network/src/service.rs
- crates/ursa-network/src/tests/service_tests.rs
- crates/ursa-network/src/utils/bloom_filter.rs
At the moment, after receiving a PUT request, nodes will send their bloom filters to the network using gossipsub.
This will significantly increase network traffic. I still think that nodes should gossip their bloom filters. If neither a node A, nor its connected peers store the requested content, but some node B on the network has it, we want node A to know about node B with some probability. However, this should be done more carefully. For example, only gossipping bloom filters every N seconds to the network.
- After receiving a PUT request, a node will no longer gossip its bloom filter to the network
- Instead, a node will send the bloom filter to its connected peers only using the request response behaviour
- If a node receives a bloom filter from a peer, it will store the bloom filter …
> feat: send cache summary using request response

- Cargo.toml
- crates/ursa-network/Cargo.toml
- crates/ursa-network/src/behaviour.rs
- crates/ursa-network/src/codec/protocol.rs
- crates/ursa-network/src/service.rs
- crates/ursa-network/src/tests/service_tests.rs
- crates/ursa-store/Cargo.toml
- crates/ursa-store/src/store.rs
This adds `rs-graphsync` to ursa service. This still needs some work and testing. I'm working on other tasks that will probably come in separate prs. In this pr we add minimal support to perform a graphsync pull request from peers.
I ended up having to fork `rs-graphsync` and downgrade `libipld` because of dependency conflicts. Opened #239 to address it in the future.
> feat: Use graphsync to pull data

- crates/ursa-gateway/Cargo.toml
- crates/ursa-gateway/src/resolver/mod.rs
- crates/ursa-gateway/src/resolver/model.rs
- crates/ursa-index-provider/src/advertisement.rs
- crates/ursa-index-provider/src/engine.rs
- crates/ursa-index-provider/src/tests/engine_tests.rs
- crates/ursa-rpc-service/src/api.rs
- crates/ursa-rpc-service/src/http/routes/network.rs
Part of #210 
The gateway needs to stream large files directly from cache node without using its internal caching. The gateway needs to know the file size to make this decision. This proposal piggybacks on metadata. 
Input:
> -rw-r--r--   1 acadia  staff   27044 Dec 18 16:50 basic.car
Command:
> curl https://0.0.0.0:80/bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei 
Output:
```
2023-01-10T16:28:22.387896Z  INFO ursa_gateway::worker: Dispatch FetchAnnounce command with cid: "bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei"
2023-01-10T16:28:22.390121Z  INFO ursa_gateway::resolver: File size received 27044
```
> feat: advertise file size

- crates/ursa-network/src/tests/service_tests.rs
service_tests contain a redundant module resulting in `ursa_network::service::service_tests::tests::*`
- remove redundant `#[cfg(test)]` and `mod tests` from service_tests.rs
- despite the git diff being wonky, there are no changes to the service tests other than removing the module and formatting
- we could also set the base module `service_tests`  to just `tests` for consistency so that they'd read: `ursa_network::service::tests::test_*`
> chore(service_tests.rs): remove redundant `mod tests`

- crates/ursa-network/src/service.rs
Debug trait introduced here 957ed5c92b5a9570cdadc821c571b19698aaf4db. Causes rocksdb mismatch. 
- Remove debug trait
> chore: revert debug trait

- crates/ursa-network/src/service.rs
- crates/ursa-rpc-service/src/api.rs
Kademlia can be too verbose
- Change `info` to `debug` logs
> chore: info to debug logs

- Cargo.toml
- crates/ursa-gateway/Cargo.toml
- crates/ursa-index-provider/Cargo.toml
- crates/ursa-metrics/Cargo.toml
- crates/ursa-network/Cargo.toml
- crates/ursa-rpc-service/Cargo.toml
- crates/ursa-store/Cargo.toml
- crates/ursa-telemetry/Cargo.toml
- crates/ursa-tracker/Cargo.toml
- crates/ursa/Cargo.toml
Localize all package related info to top-level workspace
- Change all crates to use top level workspace.package info
> chore: use localized workspace.package

- crates/ursa-gateway/example/local.toml
- crates/ursa-gateway/example/node.toml
- crates/ursa-gateway/src/cli.rs
- crates/ursa-gateway/src/config.rs
- crates/ursa-gateway/src/main.rs
- crates/ursa-gateway/src/resolver/mod.rs
- crates/ursa-gateway/src/worker/cache/mod.rs
- crates/ursa-gateway/src/worker/cache/server.rs
We don't want to cache if the content is too large.
Fixes #210 
Stream directly from node to client.
Set `cache_control_max_size = 27000 `
Input:
> -rw-r--r--   1 acadia  staff   27044 Dec 18 16:50 basic.car
Command:
> curl https://0.0.0.0:80/bafybeifyjj2bjhtxmp235vlfeeiy7sz6rzyx3lervfk3ap2nyn4rggqgei 
Output:
```
2023-01-13T20:36:44.316160Z  INFO ursa_gateway::worker::cache::server: Content size is 27044...skipping cache
at crates/ursa-gateway/src/worker/cache/server.rs:64
in ursa_gateway::worker::cache::server::Cache missed
in ursa_gateway::server::route::api::v1::get::Get car handler
in axum_tracing_opentelemetry::middleware::trace_extractor::HTTP request with otel.name: GET /:cid, http.client_ip: , http.flavor: 2.0, http.host: , http.method: GET, http.route: /:cid, http.scheme: https, …
```
> feat: gateway cache conditional

- crates/ursa-gateway/src/resolver/mod.rs
- crates/ursa-gateway/src/server/route/api/v1/get.rs
- crates/ursa-gateway/src/worker/cache/mod.rs
- crates/ursa-gateway/src/worker/cache/server.rs
- crates/ursa-gateway/src/worker/mod.rs
Prevent the server from stopping when request canceling.
Fixes:
- Solved: https://github.com/fleek-network/ursa/issues/289#issuecomment-1385797903
- Related: #289 
- Reduce log level.
- Not stop the server.
N/A
N/A
> fix(gateway): prevent server stop when request canceling

- test-plans/data-transfer/src/main.rs
- test-plans/data-transfer/src/pull.rs
We need this data for bench marking. 
Fixes #264 
Track duration of pull test plan.
```
Jan 17 18:51:54.781754	INFO	45.8881s         OK << data-transfer[008] (768df5) >> 
Jan 17 18:51:54.781843	INFO	0.0000s    MESSAGE << data-transfer[007] (0182f6) >> [Pull] Results for node 6: 5.002273377s
Jan 17 18:51:54.781895	INFO	0.0000s    MESSAGE << data-transfer[004] (c54211) >> [Pull] Results for node 3: 5.001265294s
Jan 17 18:51:54.781929	INFO	45.8866s         OK << data-transfer[007] (0182f6) >> 
Jan 17 18:51:54.781951	INFO	45.8876s         OK << data-transfer[004] (c54211) >> 
Jan 17 18:51:54.781754	INFO	0.0000s    MESSAGE << data-transfer[006] (9131bb) >> [Pull] Results for node 9: 5.001424878s
Jan 17 18:51:54.781990	INFO	0.0000s    MESSAGE << data-transfer[003] (ee6a2f) >> [Pull] Results for …
```
> feat: track duration of pull test plan

- crates/ursa-network/src/service.rs
- crates/ursa-network/src/tests/service_tests.rs
We are currently using `Bitswap::get` which fetches individual blocks. 
Fixes #300 
Use `Bitswap::sync`.
> fix: use bitswap sync to fetch dag

- .github/workflows/rust.yml
- Cargo.toml
- crates/ursa-index-provider/src/tests/mod.rs
Deprecating from fvm latest version.
Exact version of fvm
N/A
N/A
> fix: prevent fvm version from deprecated

- Cargo.toml
- crates/ursa-gateway/Cargo.toml
- crates/ursa-gateway/src/server/route/api/v1/get.rs
- crates/ursa-index-provider/Cargo.toml
- crates/ursa-index-provider/src/advertisement.rs
- crates/ursa-index-provider/src/engine.rs
- crates/ursa-index-provider/src/provider.rs
- crates/ursa-index-provider/src/signed_head.rs
- crates/ursa-index-provider/src/tests/provider_tests.rs
- crates/ursa-index-provider/src/tests/signed_head_tests.rs
- crates/ursa-network/Cargo.toml
- crates/ursa-network/src/behaviour.rs
- crates/ursa-network/src/codec/protocol.rs
- crates/ursa-network/src/service.rs
- crates/ursa-network/src/tests/service_tests.rs
- crates/ursa-rpc-service/Cargo.toml
- crates/ursa-rpc-service/src/api.rs
- crates/ursa-rpc-service/src/http/routes/network.rs
- crates/ursa-rpc-service/src/rpc/routes/network.rs
- crates/ursa-store/Cargo.toml
- crates/ursa-store/src/store.rs
- crates/ursa-store/src/tests/store_tests.rs
- test-plans/data-transfer/Cargo.toml
- test-plans/data-transfer/src/pull.rs
- test-plans/fetching/Cargo.toml
- test-plans/fetching/src/lib.rs
Addresses #239. `libipld` still has to be upgraded to 0.15 for compatibility with `rs-graphsync`.
- Remove `cid` crate dependency and import cid stuff from `libipld` crate to reduce dependency conflicts
> chore: import cid from libipld

- crates/ursa-index-provider/src/config.rs
- crates/ursa-index-provider/src/engine.rs
- crates/ursa-index-provider/src/provider.rs
- crates/ursa-index-provider/src/tests/mod.rs
- crates/ursa-rpc-service/src/config.rs
- crates/ursa-rpc-service/src/tests/mod.rs
- crates/ursa/src/config.rs
- crates/ursa/src/main.rs
First part of migrating domain from provider_config -> server_config. After some time the provider config field and migration logic can be removed completely
Fixes #244 
- add server_config.domain
- make old provider_config.domain optional 
- when loading an existing file, and the field is populated, move it to new location
- After some time, `provider_config.domain` can be completely removed
- I set the default value for domain to be `ip4/127.0.0.1/tcp/4069` for new nodes, so as to have a concrete `Multiaddr` type for the domain field. The side effect of new nodes getting this value may not be desired and if not, I can set the type back to string and have it default as empty
> chore: domain migration to `server_config` from `provider_config`

- crates/ursa-network/src/behaviour.rs
- crates/ursa-network/src/config.rs
The replication factor was hardcoded in.
- Moves the kad replication factor into `NetworkConfig`.
> chore: move kad replication factor to config

- crates/ursa-tracker/src/main.rs
Tracker is returning a ton of stale nodes to prometheus. As a first effort to curate the list of "active" nodes, we should limit to 30 days, so that old nodes/configs eventually don't get scraped
This cuts the scrape target list down from ~1500 targets to ~1100 targets, and I'm sure many more being excluded as time progresses
- We could probably use a shorter time period, like 2-3 weeks, but I went with a more generous number to avoid excluding nodes that just don't update/restart often and wouldn't reregister in time
- [n.a] I have made corresponding changes to the tests
- [n.a] I have made corresponding changes to the documentation
> feat(tracker): only provide nodes that registered within 30 days

- crates/ursa-proxy/src/core/mod.rs
- crates/ursa-proxy/src/main.rs
Safety first.
Fixes #358
```cargo run -p ursa-proxy -- daemon
Finished dev [unoptimized + debuginfo] target(s) in 0.17s
Running `target/debug/ursa-proxy daemon`
2023-02-02T21:58:27.799911Z  INFO ursa_proxy::core: Listening on 0.0.0.0:8080
at crates/ursa-proxy/src/core/mod.rs:71
2023-02-02T21:58:34.432796Z  INFO ursa_proxy::core: Shutting down servers
at crates/ursa-proxy/src/core/mod.rs:96
2023-02-02T21:58:34.433644Z  INFO ursa_proxy: Proxy shut down successfully
at crates/ursa-proxy/src/main.rs:74
```
> feat(proxy): safe shutdown

- crates/ursa-metrics/src/swarm.rs
Fixes huge numbers of tsdb series created from using unique error labels from swarm connection metrics. Such large quantities are crippling the prometheus instance causing restart loops
Name                   | value
---------------------- | -------
Number of Series	   | 2371423
Number of Chunks	   | 21758610
Number of Label Pairs  | 1286990
Current Min Time	   | 2023-02-02T20:00:00
Current Max Time       | 2023-02-03T19:45:16
Name	     | Count
------------ | -------
error	     | 1280643
request_id   | 3047
id		     | 1331
instance     | 1137
peer	     | 399
geohash	     | 157
__name__     | 103
timezone     | 45
country_code | 36
protocol     | 22
Name							  | Count
--------------------------------- | -------
swarm_outgoing_connection_error	  | 2265300
swarm_connections_incoming_error …
> fix(metrics): don't expose unique error labels for swarm connections

- crates/ursa-network/src/behaviour.rs
- crates/ursa-network/src/service.rs
- crates/ursa-network/src/tests/service_tests.rs
- crates/ursa-store/src/store.rs
The explicit `GraphSyncStore` struct is not needed, as the required trait for graphsync can be instead implemented directly on UrsaStore itself 
- remove graphsyncstorage and use ursastore directly
- construct bitswapStorage from behaviour from a single ursastore param
> refactor(store): remove GraphSyncStorage

- crates/ursa-network/src/behaviour.rs
- crates/ursa-network/src/service.rs
Allows for us to use the last known public address. Sometimes, the NAT status will fall back to private due to network idle, and the address is unknown
- increase log level for private nat status, and expand the error message to hint that the user's setup is wrong and should be fixed
- save last received public address
- [na] I have made corresponding changes to the tests
- [na] I have made corresponding changes to the documentation
> feat: save public address instead of requesting from autonat each time

- README.md
- crates/ursa-gateway/src/config.rs
- crates/ursa-index-provider/src/engine.rs
- crates/ursa-index-provider/src/provider.rs
- crates/ursa-index-provider/src/tests/mod.rs
- crates/ursa-rpc-service/src/config.rs
- crates/ursa-rpc-service/src/server.rs
- crates/ursa-rpc-service/src/tests/mod.rs
- crates/ursa/src/config.rs
- crates/ursa/src/main.rs
Autonat does not deterministically get the IP address of the node. 
- Change domain to use public IP address
> chore: manually provide ip addresses to index provider

- crates/ursa-gateway/Cargo.toml
- crates/ursa-gateway/src/cli.rs
- crates/ursa-gateway/src/config.rs
- crates/ursa-gateway/src/resolver/mod.rs
- crates/ursa-gateway/src/resolver/model.rs
- crates/ursa-gateway/src/server/mod.rs
Fixes #387
- Add cache in resolver and cache responses from indexer.
- Allow users to configure the cache.
> feat(gateway): cache indexer response

- crates/ursa-gateway/src/config.rs
- right now we use the dev cid contact so we should use the dev one
-
> chore: change default gateway indexer url

- Cargo.toml
- crates/ursa-utils/Cargo.toml
- crates/ursa-utils/src/lib.rs
- crates/ursa-utils/src/shutdown.rs
- crates/ursa/Cargo.toml
- crates/ursa/src/main.rs
- crates/ursa/src/ursa/mod.rs
This PR tries to clean up main.rs a little bit and also introduces the shutdown controller, this is the first step in having the `utils` crate, and more code will be moved to the new utils crate eventually.
Also on a logical side, previously services could fail to execute without shutting down the process, which after talking with @b0xtch, we confirmed is not the intended behavior, and the new shutdown controller makes it possible to handle these scenarios.
- create the new `ursa-utils` crate!
- refactor main.rs
- write a shutdown controller logic
- fix inconsistent sub-service failures not leading to process shutdown.
> chore: ursa main and shutdown controller

- crates/ursa-index-provider/src/engine.rs
- crates/ursa-index-provider/src/provider.rs
Invalid addresses are being published because we're mutating the address in the provider engine instead of working with a fresh copy every time we handle it.
```
INFO ursa_index_provider::provider: Announcing the advertisement with the message Message { Cid: Cid(bafy2bzaceaxrvnmnbeelm2vmjlbs7rbin4p4ovfekgezr63kqerixll7jgney), Addrs: ["/ip4/64.225.0.251/tcp/4069/http/p2p/12D3KooWQUYSiMjHVVd6BC2U2dsiaM8YhnfszAF9ruwyp99kym6a/http/p2p/12D3KooWQUYSiMjHVVd6BC2U2dsiaM8YhnfszAF9ruwyp99kym6a"], ExtraData: [] }
at crates/ursa-index-provider/src/provider.rs:185
```
- Clone and pass address.
> fix: invalid addresses are being published

- Makefile
supposedly, `cargo install` does not support workspaces properly, so at this point using it leads to different builds from `cargo build` and also different dependency trees, which means our current make file is broken.
- Remove the use of `cargo install`.
- Replace it with `mkdir -p` and `cp`.
> fix the make install command

- Cargo.toml
- Makefile
to make `cargo install` work again.
i added strum to our workspace-hack crate and it fixed it.
https://github.com/fleek-network/empty-workspace-hack/commit/c07eb1e343a455d57a5481b50eada03c62b4f2c6
> update to the latest workspace-hack

- Cargo.toml
Fixes fresh build issues by patching libp2p 0.50 to use the versions it requires to work instead of the latest prereleases. Fixes our CI pipeline as well
- patch libp2p dep with the latest 0.50.1 git version to fix libp2p-quic
> fix: use libp2p@0.50.1 git patch

- Cargo.toml
- crates/ursa-gateway/Cargo.toml
- crates/ursa-gateway/src/resolver/mod.rs
Fixes #127 
- Keep two lists, one with providers that are within a certain radius from gateway and another list of those providers outside that radius.
- Try to request content from nodes that are near us first then fallback to nodes that are further away.
- Remove providers from cache if requesting content from them fails.
- In round robin, send request to providers in each list.
```
2023-03-03T17:17:03.291219Z DEBUG ursa_gateway::resolver: 24.109.120.117 is 4092312.619 meters from host
at crates/ursa-gateway/src/resolver/mod.rs:112
2023-03-03T17:17:03.291381Z DEBUG ursa_gateway::resolver: Adding http://24.109.120.117:80 to outsider list
at crates/ursa-gateway/src/resolver/mod.rs:120
2023-03-03T17:17:03.291800Z DEBUG ursa_gateway::resolver: 167.199.91.185 is 531777.346 meters from host …
```
> feat(gateway): gateway round-robin node selection

- crates/ursa-network/src/behaviour.rs
- crates/ursa-network/src/connection.rs
- crates/ursa-network/src/lib.rs
- crates/ursa-network/src/service.rs
- crates/ursa-network/src/tests/service_tests.rs
Fixes https://github.com/fleek-network/ursa/issues/357
Too many cache requests are being sent.
- Add a manager to handle access to list of connected peers and a separate subset of that list (replication set).
- When we receive rtt from a PING, we pass the event to manager to update the replication set.
- Our assumption of rtt is that if it's high (higher than some threshold), then the peer must be far away.  High rtt could also indicate network congestion. Thus, peers will not be added to the replication set if rtt is high because we don't want to use this set to replicate content to peers who are far away and/or make network congestion worse. There are other factors that affect rtt but for the problem at hand #357, these assumptions seem reasonable. Open to suggestions of course.
> feat(node): send cache requests to peers in replication set

- crates/ursa-network/src/config.rs
- crates/ursa-network/src/service.rs
Nodes store cache summaries they receive from their peers in a map. However, the size of the map is not bounded at the moment. This can lead to too much memory usage. This PR will restrict the map size to a configurable parameter.
- Adds config parameter for the maximum number of cache summaries to store.
- If the map exceeds this number, an arbitrary cache summary is removed from the map.
> feat: limit number of stored cache summaries

- Dockerfile
Curl is required by health check
- Add dependency in apt-get command
> chore: 🤖 curl is required by health check

- crates/ursa-gateway/src/resolver/mod.rs
Atm you can't run the gateway locally without specifying some public IP and sometimes you may want to run the whole flow locally (indexer, node, gateway).
Distance computation is ignored when public IP isn't provided.
> feat(gateway): ignore distance computation when public IP isn't provided

- Cargo.toml
- crates/ursa-application/Cargo.toml
- crates/ursa-index-provider/src/provider.rs
Because we want ursa to compile!
There are 2 things wrong and one potential issue:
- The current build issue with selecting a version for fvm_ipld_encoding
- The latest forest_db commit breaks our dependence on the `Store` trait's `delete` fn and its implementation for rocksdb. We're getting this breaking change because the git dependency is unpinned to a revision and they removed the fn (ChainSafe/forest#2638)
- Noticed that `ethers-rs` was unpinned, and a breaking change there could cause more issues, and also that ursa-app is not using the workspace dep
- bump fvm_ipld_encoding to 0.3.3
- allow depreciated use of the Cbor trait in ursa-index-provider, because ipld_encoding 0.3.3 causes clippy warnings. We require our own implementation using the trait directly because the new pattern …
> fix: fvm_ipld_encoding, forest_db, and ethers dependencies

- crates/ursa-network/src/measurements/bandwidth.rs
- crates/ursa-network/src/measurements/latency.rs
- crates/ursa-network/src/measurements/mod.rs
- crates/ursa-network/src/service.rs
We need measurements for the metrics that will be used for the reputation system, see https://github.com/fleek-network/ursa/issues/452. This PR addresses latency measurements.
- Extended `MeasurementManager` so that we can register RTTs for each peer.
- Latency estimates will be computed from RTTs, assuming a symmetric latency between peers (see diagram below).
* For the diagram above, the latency will be estimated as follows:
`latency = (t4 - t1) / 2`
* We have to make the assumption that `t3 - t2` is relatively small.
> feat: latency measurements

- crates/ursa-pod/README.md
- crates/ursa-pod/examples/client.rs
- crates/ursa-pod/examples/server.rs
- crates/ursa-pod/src/client.rs
- crates/ursa-pod/src/codec.rs
- crates/ursa-pod/src/server.rs
Server should expect delivery acknowledgment from clients, and send the decryption key back for each block. it should also start splitting content into 256kb blocks
- add implementation for decryption key exchange for client and server
- refactor server implementation
- split content into 256kb blocks
- chunk blocks into 16kb chunks
- Backend trait now has a method to get a new decryption key
- add some debug logs (can be switched to trace instead)
> feat(pod): basic ufdp delivery decryption exchange

- crates/ursa-network/src/measurements/bandwidth.rs
- crates/ursa-network/src/measurements/latency.rs
- crates/ursa-network/src/measurements/mod.rs
- crates/ursa-network/src/measurements/types.rs
- crates/ursa-network/src/measurements/uptime.rs
- crates/ursa-network/src/service.rs
We need measurements for the metrics that will be used for the reputation system, see #452. This PR addresses uptime measurements.
- Extended `MeasurementManager` to include uptime estimates.
- Uptime estimates for a given peer will be computed from pings. Each ping extends the estimated uptime. If the interval between two pings is larger than 60 seconds, the uptime will be reset to 0.
- Moved all type definitions into `measurements/types.rs`.
The max interval of 60 seconds was chosen as follows:
- The ping behaviour will send a ping every 15 seconds (libp2p default).
- To account for network fluctuations, we add a grace period of 45 seconds.
- 60 seconds is likely not enough time to restart a node, so we can assume that a node has been running during those 60 seconds.
- [N/A] I have made …
> feat: uptime measurements

- Cargo.toml
The build fails because `libp2p-noise v0.41.0` is suddenly pulling in `snow v0.9.0` instead of `snow v0.9.2`.
- Pin `snow` to 0.9.2
> fix: pin snow to v0.9.2

- crates/ursa-pod/Cargo.toml
- crates/ursa-pod/benches/codec.rs
- crates/ursa-pod/benches/encrypt.rs
- crates/ursa-pod/examples/client.rs
- crates/ursa-pod/examples/server.rs
- crates/ursa-pod/src/client.rs
- crates/ursa-pod/src/codec.rs
Add basic codec benchmarking for individual frames
- add `benches/codec.rs`
- make examples exchange multiple blocks and fix client
- handle zero length:
- block (codec error)
- proof (skip proof state)
> feat(pod): codec benchmarking for frames + multiblock fixes

- crates/ursa-network/src/service.rs
Addresses https://github.com/fleek-network/ursa/issues/485.
- Cache summaries are now stored in a lru cache instead of a hashmap (this is more efficient, reduces some code, and lets us keep more recently used cache summaries)
- Removed `NetworkCommand::GetPeerContent`, since we aren't using it.
> feat: store cache summaries in lru cache

- crates/ursa-application/src/types.rs
Causing panic, preventing new users from onboarding
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: theres an err', /ursa/crates/ursa-application/src/types.rs:217:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
- Removed line with unwrap
> chore: 🤖 removes panic line which cause by init txns to state

- .github/workflows/docker-publish.yml
Add the ursa-proxy docker image build and publish in the github workflow by declaring the metadata and build steps.
⚠️ Replaces https://github.com/fleek-network/ursa/pull/509 that had the pending PR https://github.com/fleek-network/ursa/pull/506 as a dependency
- Github workflow "docker-build-push"
Depends on (refactor: 💡 ursa proxy in docker https://github.com/fleek-network/ursa/pull/506) that should be integrated first
> chore: 🤖 ursa proxy docker image builder and publisher (revisited)

- .github/workflows/docker-publish.yml
- .github/workflows/rust.yml
- .github/workflows/terraform.yml
This replaces #498. This is was mentioned on Discord by @qti3e so I thought I'd make a small PR to get familiar with the CI setup and add that filter.  Not sure if this works yet but will create the draft PRs and see.
n/a
- Each workflow file will now have a setting on the PR based triggers to only trigger on PRs that are ready for review and also filter on draft status
-  Solution from the help of Oz and https://github.com/reviewdog/action-eslint/issues/29#issuecomment-985939887
You can see the different settings and tests that were done on the superceded PR https://github.com/fleek-network/ursa/pull/498.
See note on the Terraform build - feel like we can maybe only run those on merges to main?
> chore: run CI only when not draft

- crates/ursa-proxy/Cargo.toml
- crates/ursa-proxy/README.md
- crates/ursa-proxy/src/core/handler.rs
Adds a Prometheus middleware to collect HTTP metrics.
```
curl -v http://0.0.0.0:8080/metrics
axum_http_requests_total{method="GET",status="200",endpoint="/*path"} 110001
axum_http_requests_pending{method="GET",endpoint="/*path"} 0
axum_http_requests_duration_seconds_bucket{method="GET",status="200",endpoint="/*path",le="0.005"} 3653
axum_http_requests_duration_seconds_bucket{method="GET",status="200",endpoint="/*path",le="0.01"} 17466
axum_http_requests_duration_seconds_bucket{method="GET",status="200",endpoint="/*path",le="0.025"} 92401
axum_http_requests_duration_seconds_bucket{method="GET",status="200",endpoint="/*path",le="0.05"} 108438
axum_http_requests_duration_seconds_bucket{method="GET",status="200",endpoint="/*path",le="0.1"} 109766 …
```
> feat(proxy): add metrics

- crates/ursa-pod/src/connection.rs
fixes hanging when multiple frames are read into the buffer at once
- [-] I have made corresponding changes to the tests
- [-] I have made corresponding changes to the documentation
> fix: hanging after multiple frames are read at once

- crates/ursa-proxy/README.md
- crates/ursa-proxy/src/core/handler.rs
The issue is that proxy is initializing a recorder several times which is not allowed https://docs.rs/metrics/0.21.0/metrics/fn.set_recorder.html
> An error is returned if a recorder has already been set.
- Init recorder once.
- Access metrics via admin's `/metric` endpoint.
> fix(proxy): init recorder once

- crates/ursa-pod/benchmarks/parser/main.rs
- crates/ursa-pod/benchmarks/parser/stat.rs
- crates/ursa-pod/examples/server.rs
- crates/ursa-pod/src/client.rs
- crates/ursa-pod/src/connection.rs
- crates/ursa-pod/src/instrument.rs
- crates/ursa-pod/src/server.rs
resolves todo for implementing frame filters, and improves some allocations for the inner buffer.
- add frame filter impl
- bring back read_buffer and reserve the len in the inner buffer
- whenever reading a frame, reserve the len again to make sure self.buffer always has at least 148 bytes available (max frame size)
- also added some minor cleanup in example server and ufdp-bench-parser
- improved code comments and added some todos
- [-] I have made corresponding changes to the tests
- [-] I have made corresponding changes to the documentation
> pod: frame filters and alloc improvement

- Cargo.toml
Fix for fallback panic on CONNECT requests that was initially reported here https://github.com/fleek-network/ursa/issues/522, and fix provided here https://github.com/tokio-rs/axum/pull/1958
https://github.com/fleek-network/ursa/issues/522
- Cargo.toml's axium package version as git repository and revision commit hash, until the PR (https://github.com/tokio-rs/axum/pull/1958) is integrated and release
Native build via the assisted installer
This is a test where the ursa-proxy runs along the ursa build natively through cargo commands and not via the assisted installer
> fix: 🐛 use axums fix "Fix fallback panic on CONNECT requests"
